version: '3'
services:
  # 1) nginx-reverse-proxy
  # https://github.com/jwilder/nginx-proxy
  nginx:
    build: ./nginx/build/
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro

  # 2) mysqld
  # https://hub.docker.com/_/mysql/
  mysqld:
    build: ./mysql/build/
    hostname: mysqld
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      TZ: "Asia/Tokyo"
    volumes:
      - /home/core/share/docker/mysql/data/:/var/lib/mysql

  ## any virtualhosts
  test01.localhost:
    build: ./php7-apache/build/
    volumes:
      - /home/core/share/public_html/core-01/:/var/www/html/
    environment:
      - VIRTUAL_HOST=core-01.localhost
      - CERT_NAME=shared
  test02.localhost:
    build: ./php7-apache/build/
    volumes:
      - /home/core/share/public_html/core-02/:/var/www/html/
    environment:
      - VIRTUAL_HOST=core-02.localhost
      - CERT_NAME=shared

